//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CGWork.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_CGWorkTYPE                  129
#define IDD_LIGHTS_DLG                  134
#define IDD_MATERIAL_DLG                136
#define IDD_MOUSESENSETIVE_DLG          139
#define IDD_COLOR_DLG                   140
#define IDD_PRESPECTIVE_DLG             141
#define IDD_OTHERS_DLG                  142
#define IDD_FILERENDER_DLG              143
#define IDC_LIGHT_SPACE                 1010
#define IDC_RADIO_LIGHT1                1017
#define IDC_RADIO_LIGHT2                1018
#define IDC_RADIO_LIGHT3                1019
#define IDC_RADIO_LIGHT4                1020
#define IDC_RADIO_LIGHT5                1021
#define IDC_RADIO_LIGHT6                1022
#define IDC_RADIO_LIGHT7                1023
#define IDC_RADIO_LIGHT8                1024
#define IDC_AMBL_COLOR_R                1025
#define IDC_LIGHT_ENABLED               1026
#define IDC_AMBL_COLOR_G                1027
#define IDC_AMBL_COLOR_B                1028
#define IDC_LIGHT_COLOR_R               1029
#define IDC_LIGHT_COLOR_G               1030
#define IDC_LIGHT_COLOR_B               1031
#define IDC_LIGHT_POS_X                 1032
#define IDC_LIGHT_POS_Y                 1033
#define IDC_LIGHT_POS_Z                 1034
#define IDC_LIGHT_DIR_X                 1035
#define IDC_LIGHT_DIR_Y                 1036
#define IDC_LIGHT_DIR_Z                 1037
#define IDC_LIGHT_TYPE                  1038
#define IDC_MATERIAL_AMBIENT            1039
#define IDC_MATERIAL_DIFFUSE            1040
#define IDC_EDIT_MOUSESESNSETIVE        1041
#define IDC_MATERIAL_SHININESS          1042
#define IDC_STATIC_MOUSESESNSE          1043
#define IDC_MATERIAL_SPECULAR           1044
#define IDC_BUTTON1                     1045
#define IDC_BUTTON2                     1046
#define IDC_BUTTON3                     1047
#define IDC_PRESPECTIVE_D               1048
#define IDC_EDIT_FINESS                 1049
#define IDC_EDIT_MODEL_LIST             1050
#define IDC_BUTTON4                     1051
#define IDC_BUTTON5                     1052
#define IDC_AMBIENT_MOD                 1053
#define IDC_SPECULAR_MOD                1054
#define IDC_PIC_HEIGHT                  1055
#define IDC_DIFFUSE_MOD                 1056
#define IDC_PIC_WIDTH                   1057
#define IDC_FILE_NAME                   1058
#define IDC_EDIT1                       1059
#define IDC_SPECULAR_N                  1060
#define ID_FILE_LOAD                    32771
#define ID_VIEW_ORTHOGRAPHIC            32772
#define ID_VIEW_PERSPECTIVE             32773
#define ID_ACTION_ROTATE                32774
#define ID_ACTION_TRANSLATE             32775
#define ID_ACTION_SCALE                 32776
#define ID_AXIS_X                       32777
#define ID_AXIS_Y                       32778
#define ID_AXIS_Z                       32779
#define ID_LIGHT_SHADING_FLAT           32781
#define ID_LIGHT_SHADING_GOURAUD        32782
#define ID_LIGHT_CONSTANTS              32783
#define ID_ANIM_PLAY                    32793
#define ID_ANIM_CLEAR                   32794
#define ID_ANIM_SNAPSHOT                32795
#define ID_BUTTON_SUBDIVIDE             32797
#define ID_OPTIONS_PERSPECTIVECONTROL   32798
#define ID_OPTIONS_MOUSESENSITIVITY     32799
#define ID_WIREFRAME_COLOUR             32802
#define ID_BUTTON_TRANS_TOGGLE          32805
#define ID_ACTION_RESETVIEW             32808
#define ID_AXIS_XY                      32810
#define ID_AXIS_XY32811                 32811
#define ID_BOUNDBOX                     32814
#define ID_OPTIONS_OTHEROPTIONS         32815
#define ID_POLYGON_GIVEN                32816
#define ID_POLYGON_CALCULATED           32817
#define ID_NORMAL_VERTEX                32818
#define ID_NORMAL_POLYGON               32819
#define ID_RENDER_TOFILE                32820
#define ID_VERTEX_GIVEN                 32821
#define ID_VERTEX_CALCULATED            32822
#define ID_ACTION_CLEARALL              32823
#define ID_VIEW_WIREFRAME               32824
#define ID_VIEW_SOLID                   32825
#define ID_VIEW_Z                       32826
#define ID_LIGHT_SHADING_PHONg          32827
#define ID_LIGHT_SHADING_PHON           32828
#define D_LIGHT_SHADING_PHONg           32829
#define D_LIGHT_SHADING_PHONGG          32830
#define ID_RENDER_TOSCREEN              32831
#define ID_RE                           32832
#define ID_BACKGROUND_SETIMAGE          32833
#define ID_VERTEX_CALC                  32834
#define ID_BACKGROUND_REPEAT            32835
#define ID_BACKGROUND_STRETCH           32836
#define ID_BACKGROUND_ACTIVE            32837
#define ID_OPTIONS_BACKFACECULLING      32838
#define ID_OPTIONS_NORMALINVERSE        32839
#define ID_OPTIONS_OVERRIDEGIVENNORMAL  32840
#define ID_OPTIONS_ADDSILHOUETTE        32841
#define IDC_BUTTON6                     32842
#define ID_LIGHT1POV                    32842
#define IDC_SILLHUOTTE_THICKNESS        32843
#define ID_LIGHT_LIGHT1POV              32843
#define ID_LIGHT1POV_X                  32844
#define ID_LIGHT1POV_                   32845
#define ID_LIGHT1POV_Y                  32846
#define ID_LIGHT1POV_32847              32847
#define ID_LIGHT1POV_Z                  32848
#define ID_LIGHT1POV_32849              32849
#define ID_LIGHT1POV_NEG_Z              32850
#define ID_LIGHT1POV_NEG_Y              32851
#define ID_LIGHT1POV_NEG_X              32852
#define ID_LIGHT_LIGHT1VIEW             32853

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32854
#define _APS_NEXT_CONTROL_VALUE         1058
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
